name: Lint

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_call:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install
      - name: Lint
        run: |
          yarn lint
  Typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install
      - name: Typecheck
        run: |
          yarn typecheck
