name: Test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install
      - name: Test
        run: |
          yarn test
